### ISSUE TITLE
Cannot fetch calendar from caldav.icloud.com

### ISSUE THREAD

**Issue by cmdr-dmoondra** [natelindev/tsdav#238]
I am unable to fetch the data from caldav.icloud.com, always getting the error for "cannot find homeUrl"

I am using this approach, 

const client = new DAVClient({
        serverUrl: 'https://caldav.icloud.com',
        credentials: {
          username: 'xxx@gmail.com',
          password: 'xxx',
        },
        authMethod: 'Basic',
        defaultAccountType: 'caldav',
});

and after this when i call the await client.login(); i get the error saying -> "cannot find homeUrl"

**Comment by CyrisXD** [comment]
I'm in the same boat, still trying to diagnose the issue.

**Comment by CyrisXD** [comment]
@cmdr-dmoondra Reverting back to version 2.1.2 seems to fix the issue.

**Comment by cmdr-dmoondra** [comment]
No, the issue still not fixed yet!
<img width="951" alt="Screenshot 2024-12-28 at 11 24 21 AM" src="https://github.com/user-attachments/assets/104f284d-fffb-4e47-af29-14aad8090b62" />

**Comment by nwLSteam** [comment]
I "fixed" it. iCloud does not like the `Accept-` headers that fetch uses for some reason.

First, add a `fetchOptions` to your client init that disables the headers:
```ts
const client = new DAVClient({
    // ...
    fetchOptions: {
        headers: {
            "Accept-Encoding": null as unknown as string,
            "Accept-Language": null as unknown as string,
        }
    }
});
```
(`as unknown as string` is needed because the typing is only intended to add headers, so we need to trick it to be able to remove headers)

Then, edit the library code. For me, the called file was in `dist/tsdav.cjs.js`, but unfortunately I do not know enough about JS modules to assure you that it's always that file.

Look for `const davResponse` in the function `davRequest` and replace
```js
headers: {
    "Content-Type": "application/xml",
    ...cleanupFalsy(headers),
},
```
with
```js
headers: Object.assign({
    "Content-Type": "application/xml",
    ...cleanupFalsy(headers),
}, fetchOptions.headers),
```

Now the requests should work, they succeeded for me.

@natelindev Please make `davRequest()` respect `fetchOptions`, I see it is commented out currently, which makes sense as the spread operator would override the headers if set, not add to them. I suggest using [`deepmerge`](https://www.npmjs.com/package/deepmerge) or your own implementation.

**Comment by if-nil** [comment]
When calling fetchPrincipalUrl, the HTTP header will add "accept-language: *" by default, which will cause Apple to return Internal Server Error. However, if it is not *, no error will occur. To avoid this problem, there are two temporary solutions:

low level api:
```js
import { fetchPrincipalUrl } from "tsdav";

(async () => {
  const principalUrl = await fetchPrincipalUrl({
    account: {
      serverUrl: "https://caldav.icloud.com.cn", 
      rootUrl: "https://caldav.icloud.com.cn",
      accountType: "caldav",
    },
    headers: {
      ...getBasicAuthHeaders({
      username: "{ your account id }",
      password: "{ your password }",
      }),
      "accept-language": "zh-CN,en;q=0.5",   // add "accept-language" field.  Perhaps you should set this value according to your actual situation
    },
  });
})();

```

or client api: 
```js
import { createDAVClient, getBasicAuthHeaders } from "tsdav";

(async () => {
  const client = await createDAVClient({
    serverUrl: "https://caldav.icloud.com.cn",
    credentials: {
      username: "{ your account id }",
      password: "{ your password }",
    },
    authMethod: "Custom",    // Important   use Custom
    defaultAccountType: "caldav",
    authFunction: async (credentials) => {
      return {
        ...getBasicAuthHeaders(credentials),
        "accept-language": "zh-CN,en;q=0.5",   // add "accept-language" field.  Perhaps you should set this value according to your actual situation
      };
    },
  });

  const calendars = await client.fetchCalendars();
  console.log(calendars);
})();
```


Note: The above code has only been tested on https://caldav.icloud.com.cn/   (This is a host serving Chinese customers), and not sure if other Apple hosts are available

**Comment by nwLSteam** [comment]
So `authFunction` returns headers used for every request? That wasn't clear to me (based on the naming I assumed it authenticated you manually). I guess you can use this as a better workaround then.

That said, only changing `Accept-Language` did not suffice for me. If `Accept-Encoding` stayed, I got unreadable binary data (I assume because of some compression algorithm mismatch? I didn't experiment further seeing as it worked when I removed the header).

**Comment by if-nil** [comment]
> So `authFunction` returns headers used for every request? 

Yes, I saw from the source code that the added header will be added to every request as authHeaders：
```js
  let authHeaders: Record<string, string> = {};
  switch (authMethod) {
    case 'Basic':
      authHeaders = getBasicAuthHeaders(credentials);
      break;
    case 'Oauth':
      authHeaders = (await getOauthHeaders(credentials)).headers;
      break;
    case 'Digest':
      authHeaders = {
        Authorization: `Digest ${credentials.digestString}`,
      };
      break;
    case 'Custom':
      authHeaders = (await authFunction?.(credentials)) ?? {};
      break;
    default:
      throw new Error('Invalid auth method');
  }
```

> That said, only changing `Accept-Language` did not suffice for me. If `Accept-Encoding` stayed, I got unreadable binary data (I assume because of some compression algorithm mismatch? I didn't experiment further seeing as it worked when I removed the header).

Maybe it might be true that the host is different, leading to different results (`icloud.com` and `icloud.com.cn` are isolated)

Since my project is still in development, I'm currently only using the function to get the calendar schedule. I'm not quite sure if there's still a problem with the features I'm not using


Here's a complete, example of what worked for me that might help you and others with your testing
```js
import { createDAVClient, getBasicAuthHeaders } from "tsdav";

(async () => {
  const client = await createDAVClient({
    serverUrl: "https://caldav.icloud.com.cn",
    credentials: {
      username: "{account id}",
      password: "{password}",
    },
    authMethod: "Custom",
    defaultAccountType: "caldav",
    authFunction: async (credentials) => {
      return {
        ...getBasicAuthHeaders(credentials),
        "accept-language": "zh-CN,en;q=0.5",
      };
    },
  });

  const calendars = await client.fetchCalendars();
  const obj = await client.fetchCalendarObjects({
    calendar: calendars[0],
  });
  console.log("CalendarObjects:\n", obj);
})();

```
Then run in terminal:
```shell
DEBUG=* node test.js
```
Then I can get the events that I have created on the calendar:

<img width="150" alt="image" src="https://github.com/user-attachments/assets/2d106fdc-bd78-4d83-bf27-c26395988cb0" />
 

<img width="590" alt="image" src="https://github.com/user-attachments/assets/3744eedb-ae1d-4598-a902-f23f47336239" />

**Comment by cmdr-dmoondra** [comment]
Anybody found the issue yet?

**Comment by sansjack** [comment]
also running into this issue with version `2.1.3` + `[caldav.icloud.com](https://caldav.icloud.com)`

**Comment by cmdr-dmoondra** [comment]
This is not fixed yet. Maybe this needs to be removed as anyways its not working

**Comment by cmdr-dmoondra** [comment]
We can work on this because i found out a website that works with this after adding the app specific password and the icloud email which means that it is possible

**Comment by cmdr-dmoondra** [comment]
I would love to connect and be a part of this

**Comment by SwapnilSoni1999** [comment]
I've fixed by downgrading to version 2.1.2 and adding a trailing `/` in the url

```ts
const client = await createDAVClient({
    serverUrl: "https://caldav.icloud.com/",

    credentials: {
      username: email,
      password: appSpecificPassword,
    },
    authMethod: "Basic",
    defaultAccountType: "caldav",
  })
```

**Comment by natelindev** [comment]
Sorry guys I will fix it asap

**Comment by natelindev** [comment]
fixed in v2.1.4

**Comment by pate313373** [comment]
Still the same issue in v2.1.4

`Failed to initialize CalDAV client: Error: cannot find homeUrl`
